// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BulkInsertRows(arg1:main.BulkInsertRequest):Promise<number>;

export function ChoosePrivateKeyPath():Promise<string>;

export function Connect(arg1:main.ConnectionConfig):Promise<main.ConnectionStatus>;

export function DeleteCredentials(arg1:string):Promise<void>;

export function DeleteTableRow(arg1:main.RowMutation):Promise<number>;

export function Disconnect():Promise<void>;

export function DisconnectAll():Promise<void>;

export function DisconnectProfile(arg1:string):Promise<void>;

export function Execute(arg1:string,arg2:string,arg3:string):Promise<main.QueryResult>;

export function GetTableData(arg1:main.TableDataRequest):Promise<main.TableDataResult>;

export function InsertTableRow(arg1:main.RowMutation):Promise<number>;

export function ListColumns(arg1:string,arg2:string,arg3:string):Promise<Array<main.ColumnInfo>>;

export function ListDatabases(arg1:string):Promise<Array<main.DatabaseInfo>>;

export function ListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<main.IndexInfo>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<main.TableInfo>>;

export function LoadCredentials(arg1:string):Promise<main.StoredCredentials>;

export function OpenCSVFile():Promise<string>;

export function OpenSQLFile():Promise<string>;

export function SaveCredentials(arg1:string,arg2:main.StoredCredentials):Promise<void>;

export function ShowCreateTable(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Status():Promise<main.ConnectionStatus>;

export function StatusForProfile(arg1:string):Promise<main.ConnectionStatus>;

export function TestConnection(arg1:main.ConnectionConfig):Promise<main.ConnectionStatus>;

export function UpdateTableRow(arg1:main.RowMutation):Promise<number>;
