// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BulkInsertRows(arg1) {
  return window['go']['main']['App']['BulkInsertRows'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function ChoosePrivateKeyPath() {
  return window['go']['main']['App']['ChoosePrivateKeyPath']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteCredentials(arg1) {
  return window['go']['main']['App']['DeleteCredentials'](arg1);
}

export function DeleteTableRow(arg1) {
  return window['go']['main']['App']['DeleteTableRow'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DisconnectAll() {
  return window['go']['main']['App']['DisconnectAll']();
}

export function DisconnectProfile(arg1) {
  return window['go']['main']['App']['DisconnectProfile'](arg1);
}

export function Execute(arg1, arg2, arg3) {
  return window['go']['main']['App']['Execute'](arg1, arg2, arg3);
}

export function ExecuteWithID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteWithID'](arg1, arg2, arg3, arg4);
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function InsertTableRow(arg1) {
  return window['go']['main']['App']['InsertTableRow'](arg1);
}

export function InspectSSHHostKey(arg1) {
  return window['go']['main']['App']['InspectSSHHostKey'](arg1);
}

export function ListColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListColumns'](arg1, arg2, arg3);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIndexes'](arg1, arg2, arg3);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function LoadCredentials(arg1) {
  return window['go']['main']['App']['LoadCredentials'](arg1);
}

export function OpenCSVFile() {
  return window['go']['main']['App']['OpenCSVFile']();
}

export function OpenSQLFile() {
  return window['go']['main']['App']['OpenSQLFile']();
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function ShowCreateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowCreateTable'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StatusForProfile(arg1) {
  return window['go']['main']['App']['StatusForProfile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateTableRow(arg1) {
  return window['go']['main']['App']['UpdateTableRow'](arg1);
}
